language: python

jobs:
  include:
    - services: docker
    - os: osx
      language: shell

env:
  global:
    - TWINE_USERNAME=__token__
    - CIBW_BUILD="*macosx_x86_64 *manylinux_x86_64"
    - CIBW_SKIP="cp27-* cp33-* cp34-* cp35-* pp*"
    - CIBW_BEFORE_BUILD_LINUX="pip install cmake"

install:
  - python3 -m pip install cibuildwheel==1.2.0

script:
  - python3 -m cibuildwheel --output-dir wheelhouse

after_success:
  - |
    if [[ $TRAVIS_TAG ]]; then
      python3 -m pip install twine
      python3 -m twine upload wheelhouse/*.whl
    fi
